{% set name = "astcheck" %}
{% set version = "0.4.0" %}
{% set sha256 = "e979b7450aff2b9ddc166f0533141d8a3b13ce0dfb923efa76fe9ed7c8747844" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - astcheck

about:
  home: http://github.com/takluyver/astcheck
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Check Python ASTs against templates

  description: |
    astcheck compares Python Abstract Syntax Trees against a template. This is
    useful for testing software that automatically generates or modifies Python code.
  dev_url: https://github.com/takluyver/astcheck

extra:
  recipe-maintainers:
    - takluyver
