travis:
  secure:
    BINSTAR_TOKEN: nuCrYsj/tKjpYTSF0NC3wit5CQpcLvhqwdfJ2Tay9e/TR+zOFkTMxQpGhE+lw8PU1UHzlOrnYLLqGwlvszG5bLUdUGo08bPOAl7BmW6DQ3XscEU5fOldaMHRlX/hhU+pttkwWjd3Y5LBJFQyNqH1R9eYXsUHJnegV8O5QqeYovsWDPiTkHa48s+hykV4ik6JdSSWg2ywF2b0PMJI6kVCiIT1V7bfbkst62BBrC6TImkLL9waxQmu3wcHbv49/f2+MtorrliEpuXO2v32uZGn9V4pThKJjR781L74BHJV8wT14LAhK3GPDLdHUCPrb/ThSWKr4OSo5T589rA2eM6CQD5cClMmUnLW/t9Xj2P1xjU/lHlZW5B/L0q9olff08VH280XXFqboRbxNK7dF6IrpzJeceSXDIImr+ZF2u2k7DKNO0+ZbCqbz55Q8bjc32ybFmclChur/hTuibG3Jtx9aqZwmuM/XEHyvHGUU4g+MeGdvt5xRjFxYro0lDmQjKQSpw9EhoSDChjvAblor/vLBu2MM+GwwwuZ18efQWIOmMPU6lJOnZVpOgj1fp/+Ayxo/hB3Yr5DJJYVXfYmX67vFcGRFWu9m13JFi96hjBq8vLYv2QxnxHtf0NMfDB3pqX+rcHqqMyWpHpC8PkXz5XOXlrWnhy/1JO63TnN6G2Zcgg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
