travis:
  secure:
    BINSTAR_TOKEN: MJW7+CAgcX8OJPt8xo4+JpLOdawuIdTnL9QEgurMM47QXVlQ8h6QDgUwmCbsKkqcz08R85EbjGdAA9f/N+TTynrRyZ3N0Qa1A5mghrs1qM1L0QzWzajiOFSaMf+E6Yfrj0C15IQalqTwM9zmfGbqHtzy6ElTjCYJY0ea9hPXo2D+Kq/1fKLs0ucu/DWO19WCCv01fuYw9MCCgyqhDDbuu/6nCl5HY1eKKuRJY9W23+YEvKC3YxO0+1PPhVG0PexMIH8TaLjxQMT965ITIPKDJ0komliMVdBuRCuMEEvR4bwbOZP5yDqJ/qoYnmsxAMwSX+hJdjuI7nKfTmt5zPclOtCHpaMM2VfeIDwuM0UEWWJ9+b6zIGboOKjZuLorqrCsnBEdmCfyk8Li5vyxCf7MQso4BN9u1w/l2wrpx3jfVSp/lKnK5/MgYtViJ3kOGdI+6jL6IlRJKlaRjiZD8kDAmqLjGE3015YQamJiYk3SxbwGuXLAfMsiwJPCcXV0DfotXZwHhk8UdqMkiSSxgLlKeDADDMRoe89HN1O45tzZR01jpFAG0i1Np5AIPYpGVJHG6Wv+4CEhgmJOlc4OyQGQ+VNU39F0jRXAprSDx2Oe9oltCnSOflfK1IovAQtNSuqTaeOMZL4hSutq5+NeIw8Z49hTJpyAWL5kOnBpCvxtVI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
